CREATE TABLE Produto (
idProduto INT PRIMARY KEY IDENTITY(1,1),
codBarras VARCHAR(13) NOT NULL UNIQUE,
nome VARCHAR(250) NOT NULL,
descricao VARCHAR(250) NOT NULL,
preco NUMERIC(10,2) NOT NULL,
estoque INT NOT NULL,
unidade INT NOT NULL,
tipo VARCHAR(30) NOT NULL,
ativo VARCHAR(10) NOT NULL);
