CREATE DATABASE ProjetoDS;

USE ProjetoDS;

DROP TABLE dbo.Credencial;

CREATE TABLE Pessoa (
idPessoa INT PRIMARY KEY IDENTITY(1,1),
nome VARCHAR(200) NOT NULL,
email VARCHAR(150) NOT NULL,
userName VARCHAR(100) NOT NULL,
senha VARCHAR(100) NOT NULL,
cargo VARCHAR(50) NOT NULL,
dtNascimento DATE NOT NULL,
sexo VARCHAR(15) NOT NULL,
telFixo VARCHAR(10) NULL,
telCelular VARCHAR(11) NULL,
ativo BINARY DEFAULT 1,
RG VARCHAR(25) NOT NULL,
CPF VARCHAR(11) NOT NULL);
